### PR TITLE
test support for Python=3.11

### PR DESCRIPTION
**Pull request by valeriupredoi**
we should be modern :snake:

### CODE REVIEW

**Comment by valeriupredoi** [comment]
basemap is not just yet python=3.11-supported but we are talking about it in https://github.com/conda-forge/basemap-feedstock/issues/109 - and it's the only package that needs to be py311-ed from our env, so am leaving this here til that gets sorted out :+1:

**Comment by valeriupredoi** [comment]
OK so now we have basemap supporting Python=3.11 but `nctoolkit` is not supporting 3.11 (in a masked way, no less); I am in contact with those guys via https://github.com/conda-forge/nctoolkit-feedstock/issues/58

**Comment by ledm** [comment]
Excellent work! Any significant changes we need to be aware of in python 3.11?

**Comment by valeriupredoi** [comment]
> Excellent work! Any significant changes we need to be aware of in python 3.11?

no breaking changes I am aware of - we should be good, we can always roll back to 3.10 if some of our tools misbehave

**Pull request merged**
