### PR TITLE
Updating text to bgcval2, and removing UKESM from html page.

### LINKED ISSUE #60: update bgcval text in html to bgcval2!
Time to update our branch to bgcval2 in the final reports!

### PR DESCRIPTION
**Pull request by ledm**
Changes to html to modernise text, links, and logo.

closes #60

### CODE REVIEW

**Comment by ledm** [comment]
Problem solved!

screenshot_bgcval2

**Review by ledm — COMMENTED** [review]
Happy with this. I don't think it even needs you to review it @valeriupredoi .... but github won't let me merge it without you review...

**Review by valeriupredoi — APPROVED** [review]
that one biutiful header, man :beer:

**Comment by ledm** [comment]
yeah, @DrYool should be please with the AI generated logo!

**Comment by valeriupredoi** [comment]
which reminds me - I have to check if we have a solid test for the html generation - we are doing it over the end-to-end tests, but it'd be good to have a proper dedicated test to test the pages generated - but in a different PR, this one's ready, bud!

**Pull request merged**
