### PR TITLE
Terrafirma debugging

### LINKED ISSUE #72: ESMValTool style modularisation
UKESM has changed its output netcdf format: it removed the mask! So we need to create our own masks. However, this needs to be done everywhere. This means that it needs to be added to every single function in `bgcval2/functions`.

Alternatively, I'd like to change every function so that they are modular instead, like ESMValTool. At the moment, a function both loads and applied some transformation today: ie:
```
def KtoC(nc,keys):
    """
    Loads keys[0] from the netcdf, and converts from Kelvin to Celcius.
    """
    return nc.variables[keys[0]][:] - 273.15
```
So every function takes a pre-loaded `netCDF4.Dataset` object, and a list of key names (strings), and occasionally additional kwargs. It then applied some function to those objects, and returns an arrray.

However, I propose to split the loading and the function int separate functions, such that each function only applies some operation to a list of arrays. ie:
```
def KtoC(arrays):
    """
    Converts from Kelvin to Celcius.
    """
   return [arr  - 273.15 for arr in arrays]
```

This means that with a bit of re-writing, we can do some boring stuff for every field behind the scenes. The loading, fixing the mask, etc. 

It also means that we can chain several functions together. It might make testing easier too?

### LINKED ISSUE #82: Bug running Terrafirma run
Found a bug running the TF code after yesterdays PRs. Will describe it here and fix it today.

In my defence, this bug was hidden yesterday because MASS being down meant that bgcval2 hadn't seen new ukesm data for several days so ran fine!

### PR DESCRIPTION
**Pull request by ledm**
Here's a few minor changes for Terrafirma. Including:

- Removing old code from analysis_compare.py
- Fix for weird time_counter, time_centered units
- Using "live" volume for calculating global volume means.
- Masking values that are exactly zero. 

Closes #82
Addresses but does not close #72

### CODE REVIEW

**Review by ledm — COMMENTED** [review]
Nothing too crazy here!

**Comment by ledm** [comment]
> you have a buggy bug, have a look at the [failed test](https://github.com/valeriupredoi/bgcval2/actions/runs/4172559486/jobs/7223815556) buds

It's here:
https://github.com/valeriupredoi/bgcval2/pull/87/commits/60cf6b0fcc3ae39eb441c0bfd45dc24f0322b6dd

The tests are passing netcdf filenames as a string, but the function requires an openned netcdf as a bgcval.dataset object.

Ergo: Test is wrong, not code.

**Comment by valeriupredoi** [comment]
test is never wrong - it means you have changed the handling in a function - hence the test failing is a good thing (catches that and is waiting for a fix or test change); if you have tests passing on `main` and tests failing here it means once you "fix" the test here the behaviour in `main` will make it fail. I'll have a look

**Comment by valeriupredoi** [comment]
you were missing a check on the existence of `kwargs` in `globalVolumeMean()` standard function - always good to check if stuff's there before starting to call it :grin:

**Review by valeriupredoi — APPROVED** [review]
`analysis_compare.py` has gone a paleo diet I see :laughing:

**Pull request merged**
