### PR TITLE
A series of minor changes, mostly new yml files

### PR DESCRIPTION
**Pull request by ledm**
This is a series of small changes, mostly new yml files reflecting the new Terrafirma analyses.

### CODE REVIEW

**Review by ledm — COMMENTED** [review]
No major changes, just new yml files.

**Comment by ledm** [comment]
Should be a pretty quick review for @valeriupredoi.

**Comment by ledm** [comment]
Hi @valeriupredoi. This should be a quick review. Go for it when you're ready,

**Review by valeriupredoi — APPROVED** [review]
two changed/added lines of Python - you must be in a good mood :grin:

**Comment by ledm** [comment]
Yet hours and hours of work in yml. lol.

**Pull request merged**
