### PR TITLE
Resolving the on-going issues with Jasmin permissions. 

### PR DESCRIPTION
**Pull request by ledm**
Resolving the on-going issues with Jasmin permissions. 

Continues from the merged #114.

### CODE REVIEW

**Review by valeriupredoi — APPROVED** [review]
:beers:

**Comment by valeriupredoi** [comment]
am also deleting the branch, hopefully no more need for it, if not, jyst create a new one, bud - this has been a tricky one!

**Comment by ledm** [comment]
I was right. Something else is broken here.

**Comment by ledm** [comment]
No check, I've added this fix to the PR in #116.

**Pull request merged**
