### PR TITLE
Mission Atlantic II

### PR DESCRIPTION
**Pull request by ledm**
Recent changes that didn't make it into the first Mission Atlantic PR.

### CODE REVIEW

**Comment by valeriupredoi** [comment]
oh no, the sequel :open_mouth:

**Review by ledm — COMMENTED** [review]
Checked it- found a bug. fixed it, otherwise looks fine. No actual interesting python here for @valeriupredoi to complain about.

**Review by valeriupredoi — APPROVED** [review]
if you say good, I say good :+1:

**Comment by valeriupredoi** [comment]
> > oh no, the sequel open_mouth
> 
> Mission Atlantic II: Electric Boogaloo. This time it's personal.

it doesn't look to be Breakin' anything :grin:

**Pull request merged**
