### PR TITLE
Add support for Python=3.12

### LINKED ISSUE #112: Support for Python 3.12
Just kick-starting this now, chances are it won't work just yet (am looking at you, `basemap`) but let's just see

### PR DESCRIPTION
**Pull request by valeriupredoi**
Closes #112 

- ~Indeed `basemap` is the show-stopper for now (17 Oct 2023): https://anaconda.org/conda-forge/basemap/files - not even sure if there will be any `basemap` rebuilds anyway https://github.com/conda-forge/basemap-feedstock/issues/119~ - this has been sorted out
- ~`nctoolkit` is equally unsolvable https://anaconda.org/conda-forge/nctoolkit/files~
- ~agh and I forgot about `cartopy` -> saw the incompatibility in ESMValCore~ - this too has now been sorted out, nctoolkit is the only bugger - @ledm remind me again pls, is `nctoolkit` a main dependency or we can make it optional?

~Yeh this needs to wait, bet after Christmas it'll all be dandy~

All dependencies solve for and tests pass - we have full support for Python=3.12 :partying_face:

### CODE REVIEW

**Comment by valeriupredoi** [comment]
gonna revisit imminently, things are a lot smoother Py312-wise now

**Comment by valeriupredoi** [comment]
as per https://github.com/conda-forge/basemap-feedstock/issues/119 and @molina 's efforts `baemap` is now compatible with Python 3.12 - the only problem we now have is `nctoolkit`

**Comment by valeriupredoi** [comment]
@robertjwilson and myself are sort of discussing the 3.12 support for nctoolkit in here https://github.com/pmlmodelling/nctoolkit/pull/111 - numba (as a dep for nctoolkit) is the blocker currently

**Comment by robertjwilson** [comment]
No worries @valeriupredoi . It looks like the release candidate for numba is Python 3.12 ready.  However, "Numba is currently on a Winter Break", whatever that means. So just need to wait for them to decide to push a full release to pypi https://github.com/numba/numba/issues/9197

**Comment by valeriupredoi** [comment]
cheers @robertjwilson - Winter Break sounds a bit scary - Napoleon went on such a venture in Russia and came back without an army, so hopefully they'll be back :grin:

**Comment by valeriupredoi** [comment]
@robertjwilson good news, mate! `numba` has finally come back from winter break and some 29 hours ago they finally [py312-ed](https://anaconda.org/conda-forge/numba/files) themselves :partying_face:

**Comment by robertjwilson** [comment]
OK. Just need to wait for the gears to grind at conda-forge for nctoolkit to be available for 3.12, @valeriupredoi. Essentially, we need to wait for their system to automatically re-build geoviews, and then nctoolkit.

**Comment by valeriupredoi** [comment]
> OK. Just need to wait for the gears to grind at conda-forge for nctoolkit to be available for 3.12, @valeriupredoi. Essentially, we need to wait for their system to automatically re-build geoviews, and then nctoolkit.

ya! No rush at all @robertjwilson - we needed numba to be 312-modern for another package, just wanted to drop the good news :grin:

**Comment by robertjwilson** [comment]
I have finally got nctoolkit available for python 3.12 on conda forge. Let me know if everything works at your end @valeriupredoi and I will close the issue.

**Comment by valeriupredoi** [comment]
great news @robertjwilson cheers :beer: Let me resurrect this one then

**Comment by valeriupredoi** [comment]
@ledm give this one a nod of approval pls bud, we are now modern wrt Python :snake:

**Review by ledm — APPROVED** [review]
Looks like nothing too crazy. Do you need me to test these on jasmin?

**Comment by valeriupredoi** [comment]
no not at all - if tests work then it should be fine. Cheers, bud :beer: And cheers to @robertjwilson for his work on `nctoolkit` :beer:

**Comment by robertjwilson** [comment]
Excellent @valeriupredoi

**Pull request merged**
