### PR TITLE
try catching and giving more details about the OSError from h5py netcdf4

### LINKED ISSUE #28: Exclude faulty netcdf files
Sometimes, a model produces a faulty netcdf file. This broken file is re-downloaded every time that `download_from_mass` calls it. 

There needs to be a check in `timeseriesAnalysis` or somewhere that looks for this error:
```
During handling of the above exception, another exception occurred:                                                    
                                                                                                                                                                                                                                              
Traceback (most recent call last):                                                                                     
  File "/home/users/ldemora/miniconda3/envs/bgcval2/bin/analysis_compare", line 33, in <module>                                                                                                                                               
    sys.exit(load_entry_point('BGCVal2', 'console_scripts', 'analysis_compare')())                                     
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/analysis_compare.py", line 4248, in main                                                                                                                                                
    analysis_timeseries(                                                                                               
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/analysis_timeseries.py", line 4837, in analysis_timeseries       
    tsa = timeseriesAnalysis(                                                                                          
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/timeseries/timeseriesAnalysis.py", line 121, in __init__         
    self.loadModel()                                                                                                   
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/timeseries/timeseriesAnalysis.py", line 268, in loadModel
    nc = dataset(fn, 'r')
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/bgcvaltools/dataset.py", line 47, in __init__
    self.dataset = netCDF4.Dataset(
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc'
```

At the moment, I just delete faulty files when I encounter them.

### PR DESCRIPTION
**Pull request by valeriupredoi**
Closes #28 

So there may be two solutions to the problem in #28 - that's not a problem with the file but with the system (or, user's libraries):
- one way to fix it is to have netCDF4 imported before h5py
- another is to set `HDF5_USE_FILE_LOCKING=FALSE`

At any rate, one should be absolutely clear both netCDF4 and h5py are installed from conda-forge and I will double check this for our env

### CODE REVIEW

**Comment by valeriupredoi** [comment]
OK I think with this in one shouldn't get those HDF5 issues anymore, @ledm could you test see if you still get that issue? Note you have to recreate the env and reinstall

**Comment by ledm** [comment]
Ran the command:
```
analysis_timeseries u-cn618 debug
```
with the main branch, which currently reproduces the error:
```
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc'
```
Then, checked out this branch, updated env, re-installed `pip install -e .[develop]` for good measure
and ran the same command, but it still produces the same error:
```
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc'

```

**Comment by ledm** [comment]
I also merge main into my local branch, but get the same error again.

**Comment by valeriupredoi** [comment]
OK can you post the output of these pls then?

```
conda list hdf5
conda list netcdf4
conda list h5py
```

:beer:

**Comment by ledm** [comment]
> OK can you post the output of these pls then?
> 
> ```
> conda list hdf5
> conda list netcdf4
> conda list h5py
> ```
> 
> 🍺



```
conda list hdf5
# packages in environment at /home/users/ldemora/miniconda3/envs/bgcval2:
#
# Name                    Version                   Build  Channel
hdf5                      1.12.1          nompi_h4df4325_104    conda-forge


conda list netcdf4
# packages in environment at /home/users/ldemora/miniconda3/envs/bgcval2:
#
# Name                    Version                   Build  Channel
netcdf4                   1.6.0           nompi_py39hf5a3a3f_100    conda-forge


conda list h5py
# packages in environment at /home/users/ldemora/miniconda3/envs/bgcval2:
#
# Name                    Version                   Build  Channel
h5py                      3.7.0           nompi_py39h63b1161_100    conda-forge
```

**Comment by valeriupredoi** [comment]
aha, cheers, libs look good! Did setting that env var help in any way? Also could you post the full error message pls - from Traceback beginnings

**Comment by ledm** [comment]
I set 
```
 export HDF5_USE_FILE_LOCKING=FALSE
```
and checked with:
```
echo $HDF5_USE_FILE_LOCKING
FALSE
```

Full error message:

```

timeseriesAnalysis:     loadModel:      loading new file: /gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc dataset: Unable to open %s - below more info /gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc
Your filesystem may not support HDF5 locking
Try setting HDF5_USE_FILE_LOCKING=FALSE
Traceback (most recent call last):
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/bgcvaltools/dataset.py", line 45, in __init__
    self.dataset = netCDF4.Dataset(filename, 'r', format='NETCDF4')
  File "src/netCDF4/_netCDF4.pyx", line 2353, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1963, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/ldemora/miniconda3/envs/bgcval2/bin/analysis_timeseries", line 33, in <module>
    sys.exit(load_entry_point('BGCVal2', 'console_scripts', 'analysis_timeseries')())
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/analysis_timeseries.py", line 4969, in main
    analysis_timeseries(
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/analysis_timeseries.py", line 4835, in analysis_timeseries
    tsa = timeseriesAnalysis(
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/timeseries/timeseriesAnalysis.py", line 121, in __init__
    self.loadModel()
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/timeseries/timeseriesAnalysis.py", line 268, in loadModel
    nc = dataset(fn, 'r')
  File "/home/users/ldemora/workspace/bgcval2/bgcval2/bgcvaltools/dataset.py", line 52, in __init__
    self.dataset = netCDF4.Dataset(
  File "src/netCDF4/_netCDF4.pyx", line 2353, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1963, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc'


```

**Comment by valeriupredoi** [comment]
cheers! It's catching it but the current libs setup is not helping avert it. Lemme dig a bit more

**Comment by valeriupredoi** [comment]
anyway I can grab hold of that file?

**Comment by valeriupredoi** [comment]
OK that file really is hosed - trying to load it in iris and ncdump -h -ing it fails spectacularly:

```
Traceback (most recent call last):
  File "/home/users/valeriu/bgcval2/test_hdf5err.py", line 10, in <module>
    c = iris.load(filename)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/__init__.py", line 303, in load
    return _load_collection(uris, constraints, callback).merged().cubes()
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/__init__.py", line 270, in _load_collection
    result = _CubeFilterCollection.from_cubes(cubes, constraints)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/cube.py", line 115, in from_cubes
    for cube in cubes:
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/__init__.py", line 255, in _generate_cubes
    for cube in iris.io.load_files(part_names, callback, constraints):
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/io/__init__.py", line 204, in load_files
    for cube in handling_format_spec.handler(
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/fileformats/netcdf.py", line 852, in load_cubes
    cf = iris.fileformats.cf.CFReader(filename)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/fileformats/cf.py", line 1026, in __init__
    self._dataset = netCDF4.Dataset(self._filename, mode="r")
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
OSError: [Errno -101] NetCDF: HDF error: b'/gws/nopw/j04/ukesm/BGC_data/u-cn618/u-cn618o_1y_24891201-24901201_grid_V.nc'
Exception ignored in: <function CFReader.__del__ at 0x7efef15600d0>
Traceback (most recent call last):
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/iris/fileformats/cf.py", line 1263, in __del__
    self._dataset.close()
AttributeError: 'CFReader' object has no attribute '_dataset'
```

the only way I could get a bit more info was by trying to load it in h5py:

```
Traceback (most recent call last):
  File "/home/users/valeriu/bgcval2/test_hdf5err.py", line 16, in <module>
    with h5py.File(filename, 'r') as fout:
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/h5py/_hl/files.py", line 533, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/home/users/valeriu/miniconda3-June2021/envs/esmvaltool/lib/python3.9/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 106, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 8793207, sblock->base_addr = 0, stored_eof = 41727474)
```

in other words, file is FUBAR

So it's not a miscommunication between HDF5 and netCDF4 after all, it's a crap file that's it :grin: Gonna close this since this PR introduces h5py as a dependency that we really don't need :+1:

**Pull request closed without merging**
