### PR TITLE
Skip loading files if we can

### PR DESCRIPTION
**Pull request by valeriupredoi**
@ledm can we think about https://github.com/valeriupredoi/bgcval2/issues/28#issuecomment-1208147930 here? I don't know which files can be skipped at load point, so here comes you :beer:

### CODE REVIEW

**Comment by ledm** [comment]
Changed the bool into a string, so hopefully that should clear some options for now. The default behaviour is to break, which is annoying, but should be workable for now.

This need to make this an option in other time series analyses and analysis_compare, but can't do that until PR #34 pulls through.

**Comment by valeriupredoi** [comment]
right on! It's in now :grin:

**Comment by ledm** [comment]
I think this one needs a `git merge main`  but otherwise I'm happy to merge it.

**Comment by valeriupredoi** [comment]
do we not want to add some functionality in some of the modules importing `dataset`? I'm ok with either way :+1:

**Review by ledm — APPROVED** [review]

**Comment by ledm** [comment]
Approved! Merging!

**Pull request merged**
